server:
  port: 9060
spring:
  application:
    name: authCenter
  jpa:
    show-sql: true
  redis:
    host: 192.168.24.188
    port: 6379
    password: 123456
  profiles:
    active: local
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://ljx-eureka1:9010/eureka/
logging:
  file: ../logs/lemoon.log
  level:
    org:
      springframework: debug
###feign 默认关闭熔断，请看HystrixFeignConfiguration
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000