#zuul网关
spring:
  application:
    name: ljx-gateway
server:
  port: 9030
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://ljx-eureka1:9010/eureka/,http://ljx-eureka2:9011/eureka/
    eureka-server-read-timeout-seconds:
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
    connection-request-timeout-millis: 6000
  routes:
    uaa:
#      表明鉴权认证经过zuul
      path: /uaa/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: authcenter
security:
  oauth2:
    resource:
      user-info-uri:  http://192.168.24.188:9060/user
      prefer-token-info: false
##############end#####################
####超时配置####
ribbon:
  eureka:
    enabled: true
###超时配置###