authcenter: 192.168.24.1:9030/uaa
debug: true
spring:
  application:
    name: zuul
  aop:
    proxy-target-class: true
server:
  port: 9030
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://mss-eureka1:9010/eureka/,http://mss-eureka2:9011/eureka/
logging:
  level:
    org.springframework.cloud.netflix.zuul: TRACE
zuul:
  add-host-header: true
  routes:
    oauth2:
      service-id: oauth2
      path: /uaa/**
      strip-prefix: false
      #处理http请求头为空的问题
      sensitive-headers:

security:
  oauth2:
    client:
      access-token-uri: http://oauth2/uaa/oauth/token #令牌端点
      user-authorization-uri: /uaa/oauth/authorize #授权端点
      client-id: client #OAuth2客户端ID
      client-secret: secret #OAuth2客户端密钥
    resource:
#      user-info-uri: http://authcenter/uaa/user
      jwt:
        keyValue: \
          -----BEGIN PUBLIC KEY-----\
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoZQfHaHQEzGuWBESlrcoM9DMiVM/fHEjLG7VK3COZ1xuM49P4pC+pNY3nm+wL/WM8QQdYNjPetzCiltLdW60rQa/+osW599SkmUSGF7rYXI9y4n1N4h0k9jLBdZ9n2/5miWWPDwrbsIGgLXp/NIsH4T2Gj6lUZuMj4cskIjU8P12S5TJEQ3N+PGYBY+G8zWzYB1dr3LssqATOqv1/XH+kPEesAtaaxJsfa/SWpaxDZnM5JGSjQ1/FEjyF2e0yAKbV/NqHnIqqnucr/StFBn/sGloEs1DAj8nIMtoiklqejqJvjCSdOC75f2N3iK72DgAVZkSNtfEdsVygHiOOtBtWQIDAQAB\
          -----END PUBLIC KEY-----
      id: ${spring.application.name}
      service-id: ${PREFIX:}zuul
#      token-info-uri: http://authcenter/uaa/user
#      user-info-uri: /uaa/user

ribbon:
  eureka:
    enabled: true