server:
  port: 9060
  servlet:
    context-path: /uaa

spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
  application:
    name: oauth2
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  session:
    store-type: redis
    cookie:
      name: UISESSION
  redis:
    host: 127.0.0.1
    port: 6379
    password:

  datasource:
    tomcat:
      max-active: 100
      max-idle: 200
      initial-size: 20
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource
  jackson:
    serialization:
      indent_output: true
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/**,/webjars/**,classpath:/static/js/,classpath:/templates/
  mvc:
#    view:
#      suffix: .ftl
    throw-exception-if-no-handler-found: true
  freemarker:
    charset: utf-8
    suffix: .ftl
    content-type: text/html;charset=UTF-8
    expose-session-attributes: true
  profiles:
    active: local

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://mss-eureka1:9010/eureka/,http://mss-eureka2:9011/eureka/
logging:
  file: ../logs/lemoon.log
  level:
    org:
      springframework: debug
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

security:
  oauth2:
    client:
      registered-redirect-uri: http://ljx-gateway:9030/uaa/login