server:
  port: 9011
eureka:
  instance:
    hostname: ljx-eureka2
  client:
    ##这里要覆盖application的设置，不然会读取application文件导致unavailable-replicas
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ljx-eureka1:9010/eureka/