spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8
#  切换profile，切换环境
eureka:
  server:
    #### 清理间隔（单位毫秒，默认是60*1000），开发环境设置如下可快速移除不可用的服务
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000