spring:
  application:
    name: ljx-eureka
server:
  port: 9011
eureka:
  client:
    ##这里要覆盖application的设置，不然会读取application文件导致unavailable-replicas
    service-url:
      defaultZone: http://mss-eureka1:9010/eureka/
  instance:
    hostname: mss-eureka2