server:
  port: 9010
spring:
  application:
   ##name必须一样，不然高可用会导致unavailable-replicas
    name: ljx-eureka
eureka:
  instance:
    hostname: ljx-eureka1
  client:
    ##这里要覆盖application的设置，不然会读取application文件导致unavailable-replicas
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ljx-eureka2:9011/eureka/