spring:
  application:
    name: zuul
  redis:
    port: 6379
    database: 1
    host: localhost
    password:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
#          default false and need to overwrite,so many cheater in www with no opinion
#          dispatch rule with service-id
          enabled: true
  autoconfigure:
    # TODO: remove when fixed https://github.com/spring-projects/spring-security/issues/6314
    exclude: org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          client:
            client-name: client
            client-id: client
            client-secret: secret
            provider: oauth2
            authorization-grant-type: authorization_code
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          oauth2:
            authorization-uri: http://localhost:9060/uaa/oauth/authorize
            token-uri: http://localhost:9060/uaa/oauth/token
            user-info-uri: http://localhost:9060/uaa/user
            user-name-attribute: sub
            jwk-set-uri: http://localhost:9060/uaa/oauth/token_key
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:9060/uaa/
  #            设置issuer-uri将会要求登陆
#            issuer-uri: http://localhost:9060/uaa/
  aop:
    proxy-target-class: true
  main:
    allow-bean-definition-overriding: true
server:
  port: 9030
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://mss-eureka1:9010/eureka/,http://mss-eureka2:9011/eureka/
ribbon:
  eureka:
    enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.cloud.gateway: TRACE
#    org.springframework.boot.autoconfigure: DEBUG